// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: T-RGB Gauge

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_car = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_car);
lv_obj_set_width( ui_car, 480);
lv_obj_set_height( ui_car, 480);
lv_obj_set_align( ui_car, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_car, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgcar = lv_img_create(ui_car);
lv_img_set_src(ui_imgcar, &ui_img_images_car_png);
lv_obj_set_width( ui_imgcar, LV_SIZE_CONTENT);  /// 194
lv_obj_set_height( ui_imgcar, LV_SIZE_CONTENT);   /// 392
lv_obj_set_x( ui_imgcar, 0 );
lv_obj_set_y( ui_imgcar, 450 );
lv_obj_set_align( ui_imgcar, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgcar, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgcar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Left_Button = lv_imgbtn_create(ui_Screen2);
lv_imgbtn_set_src(ui_Left_Button, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_images_left_png, NULL);
lv_imgbtn_set_src(ui_Left_Button, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_images_left_pressed_png, NULL);
lv_obj_set_width( ui_Left_Button, 140);
lv_obj_set_height( ui_Left_Button, 164);
lv_obj_set_align( ui_Left_Button, LV_ALIGN_LEFT_MID );

ui_Container_icons = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container_icons);
lv_obj_set_width( ui_Container_icons, 93);
lv_obj_set_height( ui_Container_icons, 328);
lv_obj_set_align( ui_Container_icons, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_Container_icons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon_1 = lv_img_create(ui_Container_icons);
lv_img_set_src(ui_Icon_1, &ui_img_1059536706);
lv_obj_set_width( ui_Icon_1, LV_SIZE_CONTENT);  /// 36
lv_obj_set_height( ui_Icon_1, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Icon_1, 67 );
lv_obj_set_y( ui_Icon_1, -44 );
lv_obj_set_align( ui_Icon_1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon_1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon_2 = lv_img_create(ui_Container_icons);
lv_img_set_src(ui_Icon_2, &ui_img_1059535681);
lv_obj_set_width( ui_Icon_2, LV_SIZE_CONTENT);  /// 34
lv_obj_set_height( ui_Icon_2, LV_SIZE_CONTENT);   /// 26
lv_obj_set_x( ui_Icon_2, 70 );
lv_obj_set_y( ui_Icon_2, -3 );
lv_obj_set_align( ui_Icon_2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon_2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon_3 = lv_img_create(ui_Container_icons);
lv_img_set_src(ui_Icon_3, &ui_img_1059543104);
lv_obj_set_width( ui_Icon_3, LV_SIZE_CONTENT);  /// 46
lv_obj_set_height( ui_Icon_3, LV_SIZE_CONTENT);   /// 21
lv_obj_set_x( ui_Icon_3, 71 );
lv_obj_set_y( ui_Icon_3, 42 );
lv_obj_set_align( ui_Icon_3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon_3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Icon_4 = lv_img_create(ui_Container_icons);
lv_img_set_src(ui_Icon_4, &ui_img_1059532358);
lv_obj_set_width( ui_Icon_4, LV_SIZE_CONTENT);  /// 33
lv_obj_set_height( ui_Icon_4, LV_SIZE_CONTENT);   /// 25
lv_obj_set_x( ui_Icon_4, 57 );
lv_obj_set_y( ui_Icon_4, 87 );
lv_obj_set_align( ui_Icon_4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Icon_4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Icon_4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Left_Button, ui_event_Left_Button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
