// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Moon phase

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Img_bg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Img_bg, &ui_img_images_bg_png);
lv_obj_set_width( ui_Img_bg, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_Img_bg, LV_SIZE_CONTENT);   /// 480
lv_obj_set_align( ui_Img_bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Img_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Img_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_Img_bg, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Img_bg, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container_time = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container_time);
lv_obj_set_width( ui_Container_time, 462);
lv_obj_set_height( ui_Container_time, 120);
lv_obj_set_x( ui_Container_time, 0 );
lv_obj_set_y( ui_Container_time, 100 );
lv_obj_set_align( ui_Container_time, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container_time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_time = lv_label_create(ui_Container_time);
lv_obj_set_width( ui_Label_time, 442);
lv_obj_set_height( ui_Label_time, 113);
lv_obj_set_align( ui_Label_time, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_time,"10:10:10");
lv_obj_set_style_text_align(ui_Label_time, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_time, &ui_font_OW100, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_ampm = lv_label_create(ui_Container_time);
lv_obj_set_width( ui_Label_ampm, 50);
lv_obj_set_height( ui_Label_ampm, 50);
lv_obj_set_x( ui_Label_ampm, 188 );
lv_obj_set_y( ui_Label_ampm, -23 );
lv_obj_set_align( ui_Label_ampm, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_ampm,"AM");
lv_obj_set_style_text_align(ui_Label_ampm, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_ampm, &ui_font_OW35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_sec = lv_label_create(ui_Container_time);
lv_obj_set_width( ui_Label_sec, 64);
lv_obj_set_height( ui_Label_sec, 50);
lv_obj_set_x( ui_Label_sec, 127 );
lv_obj_set_y( ui_Label_sec, 22 );
lv_obj_set_align( ui_Label_sec, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_sec,"10");
lv_obj_add_flag( ui_Label_sec, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_align(ui_Label_sec, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_sec, &ui_font_OW50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 334);
lv_obj_set_height( ui_Panel1, 54);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, -45 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 200, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x344A72), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Img_earth = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Img_earth, &ui_img_images_earth_png);
lv_obj_set_width( ui_Img_earth, LV_SIZE_CONTENT);  /// 480
lv_obj_set_height( ui_Img_earth, LV_SIZE_CONTENT);   /// 156
lv_obj_set_x( ui_Img_earth, -35 );
lv_obj_set_y( ui_Img_earth, 192 );
lv_obj_set_align( ui_Img_earth, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Img_earth, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Img_earth, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_phase = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_phase, 315);
lv_obj_set_height( ui_Label_phase, 43);
lv_obj_set_x( ui_Label_phase, 0 );
lv_obj_set_y( ui_Label_phase, -42 );
lv_obj_set_align( ui_Label_phase, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_phase,"NEW MOON");
lv_obj_set_style_text_align(ui_Label_phase, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_phase, &ui_font_OW35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_date = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_date, 315);
lv_obj_set_height( ui_Label_date, 45);
lv_obj_set_x( ui_Label_date, 0 );
lv_obj_set_y( ui_Label_date, 15 );
lv_obj_set_align( ui_Label_date, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_date,"22-JUL-24");
lv_obj_set_style_text_align(ui_Label_date, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_date, &ui_font_OW35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Img_moon = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Img_moon, &ui_img_images_moon_moon_1_png);
lv_obj_set_width( ui_Img_moon, LV_SIZE_CONTENT);  /// 170
lv_obj_set_height( ui_Img_moon, LV_SIZE_CONTENT);   /// 170
lv_obj_set_x( ui_Img_moon, -62 );
lv_obj_set_y( ui_Img_moon, -133 );
lv_obj_set_align( ui_Img_moon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Img_moon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Img_moon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
