// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: T-RGB Gauge

#ifndef _T_RGB_GAUGE_UI_H
#define _T_RGB_GAUGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void needle_Animation( lv_obj_t *TargetObject, int delay);
void carAnimation_Animation( lv_obj_t *TargetObject, int delay);
void iconAnimation_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_gauge_main;
extern lv_obj_t *ui_img_Gauge;
extern lv_obj_t *ui_img_Lettering;
extern lv_obj_t *ui_Container_temp;
extern lv_obj_t *ui_gauge_dial;
extern lv_obj_t *ui_img_needle;
extern lv_obj_t *ui_Conainer_label;
extern lv_obj_t *ui_label_speed;
void ui_event_Right_Button( lv_event_t * e);
extern lv_obj_t *ui_Right_Button;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_car;
extern lv_obj_t *ui_imgcar;
void ui_event_Left_Button( lv_event_t * e);
extern lv_obj_t *ui_Left_Button;
extern lv_obj_t *ui_Container_icons;
extern lv_obj_t *ui_Icon_1;
extern lv_obj_t *ui_Icon_2;
extern lv_obj_t *ui_Icon_3;
extern lv_obj_t *ui_Icon_4;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_images_gauge_png);   // assets/images/Gauge.png
LV_IMG_DECLARE( ui_img_images_lettering_png);   // assets/images/Lettering.png
LV_IMG_DECLARE( ui_img_images_needle_png);   // assets/images/Needle.png
LV_IMG_DECLARE( ui_img_images_right_png);   // assets/images/Right.png
LV_IMG_DECLARE( ui_img_images_right_pressed_png);   // assets/images/Right_pressed.png
LV_IMG_DECLARE( ui_img_images_car_png);   // assets/images/Car.png
LV_IMG_DECLARE( ui_img_images_left_png);   // assets/images/Left.png
LV_IMG_DECLARE( ui_img_images_left_pressed_png);   // assets/images/Left_pressed.png
LV_IMG_DECLARE( ui_img_1059536706);   // assets/images/icons/Icon-01.png
LV_IMG_DECLARE( ui_img_1059535681);   // assets/images/icons/Icon-02.png
LV_IMG_DECLARE( ui_img_1059543104);   // assets/images/icons/Icon-03.png
LV_IMG_DECLARE( ui_img_1059532358);   // assets/images/icons/Icon-05.png
LV_IMG_DECLARE( ui_img_1059533383);   // assets/images/icons/Icon-04.png
LV_IMG_DECLARE( ui_img_1059531333);   // assets/images/icons/Icon-06.png


LV_FONT_DECLARE( ui_font_Int80);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
