// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: T-RGB Gauge

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Button_Right_Pressed(lv_event_t * e);
void Screen2_Loaded(lv_event_t * e);
void Button_Left_Pressed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
