// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: T-RGB Gauge

#ifndef _T_RGB_GAUGE_UI_H
#define _T_RGB_GAUGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void caranimation_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_gauge_main;
extern lv_obj_t *ui_img_gg;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Container_temp;
extern lv_obj_t *ui_Conainer_label;
extern lv_obj_t *ui_label_speed;
void ui_event_ImgButton2( lv_event_t * e);
extern lv_obj_t *ui_ImgButton2;
extern lv_obj_t *ui_gauge_dial;
extern lv_obj_t *ui_img_dial;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
void ui_event_ImgButton3( lv_event_t * e);
extern lv_obj_t *ui_ImgButton3;
extern lv_obj_t *ui_car;
extern lv_obj_t *ui_imgcar;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_images_dial_png);   // assets/images/dial.png
LV_IMG_DECLARE( ui_img_images_numbers_png);   // assets/images/numbers.png
LV_IMG_DECLARE( ui_img_images_right_png);   // assets/images/RIGHT.png
LV_IMG_DECLARE( ui_img_1423821357);   // assets/images/RIGHT-PRESSED.png
LV_IMG_DECLARE( ui_img_images_needle_8x197_png);   // assets/images/needle_8x197.png
LV_IMG_DECLARE( ui_img_images_left_png);   // assets/images/LEFT.png
LV_IMG_DECLARE( ui_img_1557908308);   // assets/images/LEFT-PRESSED.png
LV_IMG_DECLARE( ui_img_1465642558);   // assets/images/vint-car.png


LV_FONT_DECLARE( ui_font_Int80);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
